POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "qqq",
  "password": "qqq",
  "name": "pihvi"
}
###

POST http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "qqq",
  "password": "qqq"
}
###
