@startuml
skinparam handwritten true
actor User as A
participant Browser as B
participant Server as C

A -> B: Enter address:\nhttps://fullstack-exampleapp.herokuapp.com/notes
B -> C: HTTP (over TLS) GET /notes
C --> B: Return HTML of the notes page
note left:: Parse HTML
B -> C: Get main.css
C --> B: return main.css
note left:: Parse CSS
B -> C: Get main.js
C --> B: return main.js
note left:: Parse main.js
B -> C: Get data.json
B -> B: add each item in data.json as an element to DOM
B --> A: Show the page with the form and items
@enduml
