describe('Login ', () => {
  it('front page can be opened and login works', () => {
    cy.visit('http://localhost:3000')
    cy.contains('login')
    cy.contains('blogs').should('not.exist')
    cy.get('input[type=text]')
      .type('qqq')
    cy.get('input[type=password]')
      .type('qqq')
    cy.get('input[type=submit]')
      .click()
    cy.contains('login').should('not.exist')
    cy.contains('blogs')
  })
})
